//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "novel_volumes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "novel_volumes_novel_id_volume_number_key")]
    pub novel_id: Uuid,
    #[sea_orm(unique_key = "novel_volumes_novel_id_volume_number_key")]
    pub volume_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub word_count: Option<i32>,
    pub chapter_count: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::novel_chapters::Entity")]
    NovelChapters,
    #[sea_orm(
        belongs_to = "super::novel_items::Entity",
        from = "Column::NovelId",
        to = "super::novel_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NovelItems,
}

impl Related<super::novel_chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelChapters.def()
    }
}

impl Related<super::novel_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
