//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "novel_genres")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub novel_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub genre_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genres::Entity",
        from = "Column::GenreId",
        to = "super::genres::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Genres,
    #[sea_orm(
        belongs_to = "super::novel_items::Entity",
        from = "Column::NovelId",
        to = "super::novel_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NovelItems,
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genres.def()
    }
}

impl Related<super::novel_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
