//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "novel_chapters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub novel_id: Uuid,
    pub volume_id: Option<Uuid>,
    pub chapter_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub word_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_path: Option<String>,
    pub is_vip: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_chapter_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::novel_items::Entity",
        from = "Column::NovelId",
        to = "super::novel_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NovelItems,
    #[sea_orm(
        belongs_to = "super::novel_volumes::Entity",
        from = "Column::VolumeId",
        to = "super::novel_volumes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    NovelVolumes,
}

impl Related<super::novel_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelItems.def()
    }
}

impl Related<super::novel_volumes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelVolumes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
