//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "novel_genres")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub novel_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub genre_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::genres::Entity",
        from = "Column::GenreId",
        to = "super::genres::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Genres,
    #[sea_orm(
        belongs_to = "super::novels::Entity",
        from = "Column::NovelId",
        to = "super::novels::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Novels,
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Genres.def()
    }
}

impl Related<super::novels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Novels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
