//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "novel_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "novel_files_source_id_path_key")]
    pub source_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", unique_key = "novel_files_source_id_path_key")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mime_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub checksum: Option<String>,
    pub is_available: bool,
    pub scanned_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub novel_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::novel_items::Entity",
        from = "Column::NovelId",
        to = "super::novel_items::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    NovelItems,
    #[sea_orm(
        belongs_to = "super::vfs::Entity",
        from = "Column::SourceId",
        to = "super::vfs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vfs,
}

impl Related<super::novel_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelItems.def()
    }
}

impl Related<super::vfs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vfs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
