//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "novels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    pub scrape_enabled: bool,
    pub scrape_agents: Vec<String>,
    pub sort_order: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub settings: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub sources: Json,
    #[sea_orm(column_type = "Text")]
    pub sync_status: String,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::novel_items::Entity")]
    NovelItems,
}

impl Related<super::novel_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
