//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "novels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub app_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub author: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub serial_status: Option<String>,
    pub word_count: Option<i32>,
    pub year: Option<i32>,
    pub last_updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "novels_source_provider_source_book_id_key"
    )]
    pub source_provider: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "novels_source_provider_source_book_id_key"
    )]
    pub source_book_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    pub is_adult: bool,
    pub is_favorite: bool,
    pub locked_fields: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub douban_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub bangumi_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub douban_rating: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bangumi_rating: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub isbn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub publisher: Option<String>,
    pub scraped_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub qidian_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apps::Entity",
        from = "Column::AppId",
        to = "super::apps::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Apps,
    #[sea_orm(has_many = "super::media_arts::Entity")]
    MediaArts,
    #[sea_orm(has_many = "super::media_credits::Entity")]
    MediaCredits,
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(has_many = "super::novel_chapters::Entity")]
    NovelChapters,
    #[sea_orm(has_many = "super::novel_collections::Entity")]
    NovelCollections,
    #[sea_orm(has_many = "super::novel_genres::Entity")]
    NovelGenres,
    #[sea_orm(has_many = "super::novel_tags::Entity")]
    NovelTags,
    #[sea_orm(has_many = "super::novel_volumes::Entity")]
    NovelVolumes,
    #[sea_orm(has_many = "super::user_media_ratings::Entity")]
    UserMediaRatings,
    #[sea_orm(has_many = "super::user_media_states::Entity")]
    UserMediaStates,
}

impl Related<super::apps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}

impl Related<super::media_arts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaArts.def()
    }
}

impl Related<super::media_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaCredits.def()
    }
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::novel_chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelChapters.def()
    }
}

impl Related<super::novel_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelCollections.def()
    }
}

impl Related<super::novel_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelGenres.def()
    }
}

impl Related<super::novel_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelTags.def()
    }
}

impl Related<super::novel_volumes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NovelVolumes.def()
    }
}

impl Related<super::user_media_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaRatings.def()
    }
}

impl Related<super::user_media_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMediaStates.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        super::novel_collections::Relation::Collections.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::novel_collections::Relation::Novels.def().rev())
    }
}

impl Related<super::genres::Entity> for Entity {
    fn to() -> RelationDef {
        super::novel_genres::Relation::Genres.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::novel_genres::Relation::Novels.def().rev())
    }
}

impl Related<super::media_tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::novel_tags::Relation::MediaTags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::novel_tags::Relation::Novels.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
